name: Package and publish addon
on:
# Ideally this would be triggered by a release on the GitHub UI,
# but actions-kicad-addon insists on owning the release process
#  release:
#    types: [published]
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: cooked/actions-kicad-addon@v0.1.0
        with:
          version: ${{ github.ref_name }}
          status: "development"
          deploy: false
