name: Package and publish addon
on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: cooked/actions-kicad-addon@v0.1.0
        with:
          # TODO: actions-kicad-addon tacks on a v in front of the version, so we have to undo that here
          # this is a total hack
          version: ${{ replace(github.ref_name, 'v', '') }}
          status: "development"
          deploy: false
          # TODO: deduplicate; the following is duplicated with the current metadata skeleton
          # unfortunately actions-kicad-addon insists on owning all the fields
          desc: "A plugin to replicate, load, and save layouts of hierarchical sheets."
          kicad_version: "8.0"
          license: "BSD-3-clause"
